// AUTO-GENERATED by tauri-specta — DO NOT EDIT.
// Source: apps/desktop/src-tauri/src/ipc_spec.rs (Phase 1 plan 01-03).
// Regenerate with: `cargo run --bin specta-emit`.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<string> {
    return await TAURI_INVOKE("ping");
},
async appInfo() : Promise<Result<AppInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storeSecret(service: string, account: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("store_secret", { service, account, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSecret(service: string, account: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_secret", { service, account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSecret(service: string, account: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_secret", { service, account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Smoke command — panics on a worker thread so we can prove the panic
 * hook in `panic_hook.rs` catches cross-thread panics and emits the
 * `app:panic` event to the renderer.
 * 
 * In release builds this is a no-op that returns
 * `AppError::InvalidArgument("trigger_panic disabled in release")` —
 * the renderer button is hidden in release UIs. This keeps the IPC
 * surface stable across debug/release so `tauri-specta`-generated TS
 * bindings don't drift between profiles.
 */
async triggerPanic() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_panic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch a story against both drivers and stream events to the renderer.
 * 
 * `on_event` is a typed `Channel<ExecutorEvent>` that the renderer holds
 * open for the duration of the run; the host pumps every event from the
 * executor mpsc receiver into the channel.
 */
async launchAutomation(storySource: string, projectFolder: string, onEvent: TAURI_CHANNEL<AutomationEvent>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_automation", { storySource, projectFolder, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDisplays() : Promise<Result<DisplayInfoDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_displays") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkScreenCapturePermission() : Promise<Result<PermissionState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_screen_capture_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openScreenCapturePrefs() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_screen_capture_prefs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async relaunchApp() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("relaunch_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCapture(cfg: CaptureConfigDto, onEvent: TAURI_CHANNEL<CaptureEventDto>, onFrame: TAURI_CHANNEL<FrameMetaDto>) : Promise<Result<SessionId, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture", { cfg, onEvent, onFrame }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopCapture(session: SessionId) : Promise<Result<CaptureStatsDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_capture", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ENC-02 — runtime HW-encoder feature detection. Safe to call at any
 * time; callers SHOULD cache the result for the session.
 */
async probeHwEncoders() : Promise<Result<EncoderProbeDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_hw_encoders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start an end-to-end recording: capture pipeline → encoder pipeline →
 * MP4/H.264 file at `<project_folder>/exports/<session_id>.mp4`.
 * 
 * Automation orchestration (Plan 01-06 BrowserDriver) runs independently
 * via `launch_automation`; the UI correlates the two by session id.
 */
async startRecording(args: StartRecordingArgs, onEvent: TAURI_CHANNEL<RecordingEvent>) : Promise<Result<RecordingSessionId, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { args, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRecording(session: RecordingSessionId, onEvent: TAURI_CHANNEL<RecordingEvent>) : Promise<Result<EncodeResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording", { session, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a `.story` source string and return best-effort AST + diagnostics.
 * 
 * The parser is guaranteed non-panicking on valid UTF-8; the 10 MB byte cap
 * is enforced at the higher `story_parser::io::parse_file` layer — this
 * command accepts an already-loaded string (the renderer owns the buffer,
 * CodeMirror virtualizes large files). If you need the hard cap here,
 * check `source.len() <= story_parser::MAX_STORY_FILE_BYTES` first.
 */
async parseStory(source: string) : Promise<Result<ParseResultDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_story", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<ProjectDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProject(args: CreateProjectArgs) : Promise<Result<ProjectDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openProject(args: ProjectIdArg) : Promise<Result<ProjectFolderInfoDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProject(args: ProjectIdArg) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_project", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { kind: "Io"; message: string } | { kind: "Serialization"; message: string } | { kind: "Keyring"; message: string } | { kind: "Automation"; message: string } | { kind: "Capture"; message: string } | { kind: "Encoder"; message: string } | { kind: "Storage"; message: string } | { kind: "NotFound"; message: string } | { kind: "InvalidArgument"; message: string } | { kind: "Internal"; message: string }
export type AppInfo = { version: string; platform: string; arch: string; data_dir: string; log_dir: string }
/**
 * Tauri / specta wrapper around `automation::ExecutorEvent`.
 * 
 * The `automation` crate is pure (D-11) — it doesn't depend on `specta`.
 * We wrap its event into a JSON `Value` here so the `Channel<T>` payload
 * type satisfies `specta::Type` without leaking Tauri into `automation`.
 */
export type AutomationEvent = { 
/**
 * JSON-stringified `automation::ExecutorEvent` (the event enum is
 * defined in the pure `automation` crate which deliberately doesn't
 * depend on `specta`; the renderer parses with `JSON.parse`).
 */
json: string }
export type CaptureConfigDto = { display_id: bigint; include_cursor: boolean; fps_target: number; pixel_format: PixelFormatDto; 
/**
 * Defaults to 256 MiB if `None`.
 */
queue_cap_bytes: bigint | null }
/**
 * Wrapper around `capture::CaptureEvent` for the typed `Channel<T>` —
 * same pattern as `AutomationEvent` in `commands/automation.rs`. Keeps
 * the `capture` crate free of `specta`.
 */
export type CaptureEventDto = { json: string }
export type CaptureStatsDto = { frames_delivered: bigint; frames_dropped: bigint; bytes_peak: bigint; duration_ms: bigint }
export type ClockSourceDto = "host-time" | "qpc" | "synthetic"
export type CommandDto = { verb: "navigate"; url: string; span: SpanDto } | { verb: "click"; target: SelectorOrTextDto; span: SpanDto } | { verb: "type"; target: SelectorOrTextDto; text: string; span: SpanDto } | { verb: "scroll"; direction: ScrollDirDto; amount: number | null; span: SpanDto } | { verb: "hover"; target: SelectorOrTextDto; span: SpanDto } | { verb: "drag"; from: SelectorOrTextDto; to: SelectorOrTextDto; span: SpanDto } | { verb: "select"; target: SelectorOrTextDto; value: string; span: SpanDto } | { verb: "upload"; target: SelectorOrTextDto; path: string; span: SpanDto } | { verb: "wait"; duration_ms: bigint; span: SpanDto } | { verb: "wait-for"; target: SelectorOrTextDto; timeout_ms: bigint | null; span: SpanDto } | { verb: "assert"; target: SelectorOrTextDto; span: SpanDto } | { verb: "screenshot"; name: string; span: SpanDto } | { verb: "pause"; span: SpanDto }
export type CreateProjectArgs = { name: string; 
/**
 * Parent directory to create the project folder under. The folder
 * name itself is derived from `name` via slugification (see
 * `storage::project_folder::create_project`).
 */
parent: string }
export type DiagnosticDto = { severity: SeverityDto; message: string; span: SpanDto; suggestion: string | null }
export type DisplayInfoDto = { id: bigint; name: string; width_px: number; height_px: number; scale_factor: number; is_primary: boolean }
export type EncodeProgressDto = { frame: bigint; fps: number; bitrate_kbps: number; out_time_ms: bigint; drop_frames: bigint; dup_frames: bigint; speed: number; finished: boolean }
export type EncodeResultDto = { output_path: string; duration_ms: bigint; bytes: bigint; frames_written: bigint; frames_dropped: bigint }
export type EncoderProbeDto = { available: HardwareEncoderDto[]; preferred: HardwareEncoderDto }
export type FrameMetaDto = { sequence: bigint; 
/**
 * PTS in nanoseconds (i128 doesn't cross IPC cleanly; values fit
 * comfortably in i64 over any realistic capture duration).
 */
pts_ns: bigint; clock_source: ClockSourceDto; bytes: bigint; width_px: number; height_px: number }
export type HardwareEncoderDto = "video-toolbox-h264" | "video-toolbox-hevc" | "nvenc-h264" | "qsv-h264" | "amf-h264" | "openh-264-software"
export type MetaDto = { app: string | null; viewport: ViewportDto | null; theme: ThemeDto | null; speed: number | null; span: SpanDto }
export type PanicPayload = { 
/**
 * Sanitized panic message. Backtrace is NOT included (file-only).
 */
message: string; 
/**
 * Name of the thread that panicked, or "unknown".
 */
thread: string }
export type ParseResultDto = { ast: StoryDto | null; diagnostics: DiagnosticDto[] }
/**
 * macOS-only permission state mirroring `capture::macos::tcc::PermissionState`.
 * On non-macOS this command always returns `Granted`.
 */
export type PermissionState = "granted" | "denied" | "undetermined"
export type PixelFormatDto = "bgra" | "nv-12"
/**
 * DTO mirror of `storage::Project`. Serializes `Uuid` as a string and
 * `PathBuf` as a string so the renderer sees plain JSON. `last_opened_at`
 * is `i64` millis since epoch (the renderer converts to `Date`).
 */
export type ProjectDto = { id: string; name: string; folder_path: string; created_at: bigint; last_opened_at: bigint | null; thumbnail_path: string | null }
/**
 * Returned by `open_project` — enough context for the editor to load
 * the story file and show recent-session counts. The renderer uses
 * `folder_path` + `story_path` to read/write via `tauri-plugin-fs`.
 */
export type ProjectFolderInfoDto = { id: string; name: string; folder_path: string; story_path: string; exports_dir: string; session_count: bigint }
export type ProjectIdArg = { id: string }
/**
 * Unified recording event — fan-in of capture / encode progress /
 * terminal results. We don't wire automation executor events here
 * (Plan 01-06 already streams those on its own channel); the UI joins
 * the two streams via the session id.
 */
export type RecordingEvent = { type: "capture-status"; json: string } | { type: "encode-progress"; progress: EncodeProgressDto } | { type: "completed"; result: EncodeResultDto } | { type: "failed"; message: string }
export type RecordingSessionId = string
export type SceneDto = { name: string; commands: CommandDto[]; span: SpanDto }
export type ScrollDirDto = "up" | "down" | "left" | "right"
export type SelectorOrTextDto = { kind: "text"; value: string } | { kind: "selector"; value: string } | { kind: "test_id"; value: string } | { kind: "aria"; value: string }
export type SessionId = string
export type SeverityDto = "error" | "warning" | "info"
export type SpanDto = { start: number; end: number; line: number; col: number }
export type StartRecordingArgs = { project_folder: string; display_id: bigint; width: number; height: number; fps: number }
export type StoryDto = { name: string | null; meta: MetaDto; scenes: SceneDto[]; span: SpanDto }
export type TAURI_CHANNEL<TSend> = null
export type ThemeDto = "light" | "dark" | "auto"
export type ViewportDto = { width: number; height: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
