// StoryCapture desktop host (Phase 1 plan 01-03).
//
// `run()` is the single entry point; `main.rs` is a 5-line shim. The host
// registers 9 Tauri plugins (log, fs, dialog, updater, window-state, shell,
// process, single-instance, os), wires the typed IPC surface from
// `ipc_spec`, installs the panic hook (D-31, T-03-04) and the
// `tracing` ↔ `tauri-plugin-log` bridge (D-30), and exposes `AppState`
// with a paths-+-actor-registry shape (D-06).
//
// OS keychain access (D-29) is exposed via the `system::store_secret`,
// `system::load_secret`, `system::delete_secret` commands using the
// `keyring` crate directly — no separate Tauri plugin is needed because
// the cross-platform binding already targets all three platform stores
// (macOS Keychain, Windows Credential Manager, Linux Secret Service).

pub mod commands;
pub mod error;
pub mod ipc_spec;
pub mod logging;
pub mod panic_hook;
pub mod state;

use tauri::Manager;

/// Boot the host. Exits the process when Tauri's main loop returns.
pub fn run() {
    let specta_builder = ipc_spec::builder();

    // In debug builds, emit fresh TS bindings on every launch.
    #[cfg(debug_assertions)]
    {
        if let Err(e) = specta_builder.export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::BigInt)
                .header("// AUTO-GENERATED by tauri-specta — DO NOT EDIT.\n// Source: apps/desktop/src-tauri/src/ipc_spec.rs (Phase 1 plan 01-03).\n"),
            ipc_spec::TS_BINDINGS_PATH,
        ) {
            // Don't abort startup — the renderer doesn't require fresh
            // bindings to launch, and a missing target dir during early
            // bring-up shouldn't block `cargo run`.
            eprintln!("[storycapture] specta TS export failed: {e}");
        }
    }

    let invoke_handler = specta_builder.invoke_handler();

    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            // Re-focus the existing main window when a second instance is launched.
            if let Some(win) = app.get_webview_window("main") {
                let _ = win.unminimize();
                let _ = win.set_focus();
            }
        }))
        .plugin(tauri_plugin_log::Builder::default()
            .level(log::LevelFilter::Info)
            .max_file_size(50 * 1024 * 1024 /* 50 MiB */)
            .rotation_strategy(tauri_plugin_log::RotationStrategy::KeepAll)
            .build())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_os::init())
        .setup(|app| {
            // Resolve platform paths.
            let log_dir = app
                .path()
                .app_log_dir()
                .map_err(|e| format!("resolving app_log_dir: {e}"))?;
            let data_dir = app
                .path()
                .app_data_dir()
                .map_err(|e| format!("resolving app_data_dir: {e}"))?;

            // tracing -> file (D-30). tauri-plugin-log handles its own
            // file in the same dir; the two are complementary surfaces.
            if let Err(e) = logging::init(&log_dir) {
                eprintln!("[storycapture] tracing init failed: {e}");
            }

            // Install AppState BEFORE panic hook so any panic path can
            // safely look up the data dir.
            app.manage(state::AppState::new(data_dir, log_dir));

            // LSP bridge (D-16, Plan 03-14): in-process tower-lsp via IPC.
            app.manage(commands::lsp::LspBridgeState(
                intelligence::lsp::LspBridge::new(),
            ));

            // Panic hook last — needs an AppHandle for event emit.
            panic_hook::install(app.handle().clone());

            tracing::info!(target: "storycapture::boot", "host setup complete");
            Ok(())
        })
        .invoke_handler(invoke_handler)
        .run(tauri::generate_context!())
        .expect("tauri::run failed");
}
