// StoryCapture desktop host.
//
// `run()` is the single entry point; `main.rs` is a thin shim. The host
// registers Tauri plugins, wires the typed IPC surface from `ipc_spec`,
// installs the panic hook and the `tracing` ↔ `tauri-plugin-log` bridge,
// and exposes `AppState`.
//
// OS keychain access uses the `keyring` crate directly — no separate
// Tauri plugin is needed because the cross-platform binding already
// targets all three platform stores (macOS Keychain, Windows Credential
// Manager, Linux Secret Service).

pub mod author_driver;
pub mod commands;
pub mod error;
pub mod ipc_spec;

pub use commands::simulator::prune_runs_retain_5;
pub mod logging;
pub mod panic_hook;
pub mod state;
pub mod title_hints;

use tauri::{
    menu::{Menu, MenuItemBuilder, PredefinedMenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    AppHandle, Manager, Runtime,
};

const TRAY_OPEN_MENU_ID: &str = "tray_open_main_window";
const TRAY_QUIT_MENU_ID: &str = "tray_quit_app";

fn focus_main_window<R: Runtime>(app: &AppHandle<R>) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.show();
        let _ = window.unminimize();
        let _ = window.set_focus();
    }
}

fn setup_tray<R: Runtime>(app: &AppHandle<R>) -> tauri::Result<()> {
    let open_item = MenuItemBuilder::with_id(TRAY_OPEN_MENU_ID, "Open StoryCapture").build(app)?;
    let separator = PredefinedMenuItem::separator(app)?;
    let quit_item = MenuItemBuilder::with_id(TRAY_QUIT_MENU_ID, "Quit").build(app)?;
    let menu = Menu::with_items(app, &[&open_item, &separator, &quit_item])?;

    let mut tray = TrayIconBuilder::with_id("storycapture-tray")
        .menu(&menu)
        .tooltip("StoryCapture")
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| match event.id().as_ref() {
            TRAY_OPEN_MENU_ID => focus_main_window(app),
            TRAY_QUIT_MENU_ID => app.exit(0),
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                focus_main_window(tray.app_handle());
            }
        });

    if let Some(icon) = app.default_window_icon().cloned() {
        tray = tray.icon(icon);
    }

    tray.build(app)?;
    Ok(())
}

/// Boot the host. Exits the process when Tauri's main loop returns.
pub fn run() {
    let specta_builder = ipc_spec::builder();

    // In debug builds, emit fresh TS bindings on every launch.
    #[cfg(debug_assertions)]
    {
        if let Err(e) = specta_builder.export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::BigInt)
                .header("// @ts-nocheck\n// AUTO-GENERATED by tauri-specta — DO NOT EDIT.\n// Source: apps/desktop/src-tauri/src/ipc_spec.rs (Phase 1 plan 01-03).\n"),
            ipc_spec::TS_BINDINGS_PATH,
        ) {
            // Don't abort startup — the renderer doesn't require fresh
            // bindings to launch, and a missing target dir during early
            // bring-up shouldn't block `cargo run`.
            eprintln!("[storycapture] specta TS export failed: {e}");
        }
    }

    let invoke_handler = specta_builder.invoke_handler();

    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            // Re-focus the existing main window when a second instance is launched.
            focus_main_window(app);
        }))
        .plugin(
            // Renderer-facing `log:` IPC. The canonical logger/file is
            // owned by `tracing` (see `logging::init`); skip the plugin's
            // global logger so `tracing_log::LogTracer` can bridge `log`
            // records into the same session-prefixed file.
            tauri_plugin_log::Builder::default()
                .level(log::LevelFilter::Info)
                .max_file_size(10 * 1024 * 1024 /* 10 MiB */)
                .rotation_strategy(tauri_plugin_log::RotationStrategy::KeepSome(10))
                .skip_logger()
                .build(),
        )
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_store::Builder::default().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_os::init())
        .setup(|app| {
            // Resolve platform paths.
            let log_dir = app
                .path()
                .app_log_dir()
                .map_err(|e| format!("resolving app_log_dir: {e}"))?;
            let data_dir = app
                .path()
                .app_data_dir()
                .map_err(|e| format!("resolving app_data_dir: {e}"))?;

            // tracing -> file. tauri-plugin-log handles its own file in
            // the same dir; the two are complementary surfaces. The
            // user-configurable rotation policy + log-dir override
            // (see Settings → Logs) is honoured by `tracing` here.
            let app_settings = commands::app_settings::load(app.handle());
            if let Err(e) = logging::init(&log_dir, &app_settings.log) {
                eprintln!("[storycapture] tracing init failed: {e}");
            }

            // Install AppState BEFORE panic hook so any panic path can
            // safely look up the data dir.
            app.manage(state::AppState::new(data_dir, log_dir));

            // Author-time simulator session registry.
            app.manage(commands::simulator::SimulatorRegistry::default());

            // Shared author-driver FSM. Arc-managed so PickerResumeGuard
            // can clone a handle for deferred restore.
            app.manage(std::sync::Arc::new(
                author_driver::AuthorDriverRegistry::default(),
            ));

            // LSP bridge: in-process tower-lsp via IPC.
            // `LspBridge::new()` returns (bridge, drain_future) — the drain
            // must be spawned on a Tokio runtime. `tauri::async_runtime::spawn`
            // works during setup; plain `tokio::spawn` does not.
            let (lsp_bridge, lsp_drain) = intelligence::lsp::LspBridge::new();
            tauri::async_runtime::spawn(lsp_drain);
            app.manage(commands::lsp::LspBridgeState::new(lsp_bridge));

            // NL task registry: abort handles for in-flight NL turns.
            // Wrapped in Arc so spawned tasks can clone and hold a reference
            // beyond the Tauri command lifetime.
            app.manage(std::sync::Arc::new(
                state::nl_tasks::NlTaskRegistry::default(),
            ));

            // Panic hook last — needs an AppHandle for event emit.
            panic_hook::install(app.handle().clone());

            // Keep a real system tray / menu bar affordance available while the
            // app is running instead of relying on bundle metadata alone.
            setup_tray(app.handle())?;

            // macOS-only: `tauri dev` runs the raw binary (no .app bundle),
            // so the Dock falls back to a generic executable glyph. Set the
            // Dock icon at runtime from the compiled-in PNG so dev matches
            // the bundled build.
            #[cfg(target_os = "macos")]
            set_macos_dock_icon();

            tracing::info!(target: "storycapture::boot", "host setup complete");
            Ok(())
        })
        .invoke_handler(invoke_handler)
        .build(tauri::generate_context!())
        .expect("tauri::run failed")
        .run(|app_handle, event| {
            if matches!(
                event,
                tauri::RunEvent::ExitRequested { .. } | tauri::RunEvent::Exit
            ) {
                drain_author_preview_sessions(app_handle);
                crate::commands::encode::drain_recording_sessions(app_handle);
            }
        });
}

/// Best-effort synchronous teardown of author-preview sessions at app exit.
/// Aborts pump tasks and drops the driver Arcs so the sidecar children
/// close stdin → Chromium exits cleanly. Tolerates mid-flight locks by
/// giving up after `try_lock` — the OS will reap leaked processes.
fn drain_author_preview_sessions(app_handle: &AppHandle) {
    let Some(state) = app_handle.try_state::<crate::state::AppState>() else {
        return;
    };
    let Ok(mut sessions) = state.author_preview_sessions.try_lock() else {
        return;
    };
    for (_stream_id, mut session) in sessions.drain() {
        if let Some(pump) = session.pump.take() {
            pump.abort();
        }
    }
}

/// Set the macOS Dock icon at runtime from the compiled-in PNG.
///
/// Needed because `tauri dev` on macOS runs `target/debug/storycapture`
/// directly rather than a proper `.app` bundle, so there is no
/// `Info.plist` or embedded `.icns` for the Dock to read. The compiled
/// release bundle uses `bundle.icon` from `tauri.conf.json` and does
/// not need this path, but calling it unconditionally is harmless.
#[cfg(target_os = "macos")]
fn set_macos_dock_icon() {
    use objc2::AnyThread;
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::{MainThreadMarker, NSData};

    let Some(mtm) = MainThreadMarker::new() else {
        // Not on the main thread — Tauri's setup() runs on main, so this
        // branch should not hit, but we fail open rather than crash.
        return;
    };

    let png_bytes: &[u8] = include_bytes!("../icons/icon.png");

    unsafe {
        let data = NSData::with_bytes(png_bytes);
        let Some(image) = NSImage::initWithData(NSImage::alloc(), &data) else {
            return;
        };
        let app = NSApplication::sharedApplication(mtm);
        app.setApplicationIconImage(Some(&image));
    }
}
