// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Command = { "verb": "navigate", url: string, span: Span, } | { "verb": "click", target: SelectorOrText, span: Span, } | { "verb": "type", target: SelectorOrText, text: string, span: Span, } | { "verb": "scroll", direction: ScrollDir, amount: number | null, span: Span, } | { "verb": "hover", target: SelectorOrText, span: Span, } | { "verb": "drag", from: SelectorOrText, to: SelectorOrText, span: Span, } | { "verb": "select", target: SelectorOrText, value: string, span: Span, } | { "verb": "upload", target: SelectorOrText, path: string, span: Span, } | { "verb": "wait", duration_ms: bigint, span: Span, } | { "verb": "wait-for", target: SelectorOrText, timeout_ms: bigint | null, span: Span, } | { "verb": "assert", target: SelectorOrText, span: Span, } | { "verb": "screenshot", name: string, span: Span, } | { "verb": "pause", span: Span, };

export type Diagnostic = { severity: Severity, message: string, span: Span, suggestion: string | null, };

export type Meta = { app: string | null, viewport: Viewport | null, theme: Theme | null, speed: number | null, span: Span, };

/**
 * Result of parsing a `.story` source string.
 *
 * `ast` is `Some` even when `diagnostics` is non-empty (best-effort AST,
 * per DSL-06 panic-mode recovery).
 */
export type ParseResult = { ast: Story | null, diagnostics: Array<Diagnostic>, };

export type Scene = { name: string, commands: Array<Command>, span: Span, };

export type ScrollDir = "up" | "down" | "left" | "right";

export type SelectorOrText = { "kind": "text", "value": string } | { "kind": "selector", "value": string } | { "kind": "test_id", "value": string } | { "kind": "aria", "value": string };

export type Severity = "error" | "warning" | "info";

/**
 * Source span (byte offsets + 1-indexed line/col of `start`).
 */
export type Span = { start: number, end: number, line: number, col: number, };

export type Story = { name: string | null, meta: Meta, scenes: Array<Scene>, span: Span, };

export type Theme = "light" | "dark" | "auto";

export type Viewport = { width: number, height: number, };
