/**
 * AI Disclosure Modal — EU AI Act Article 50 export-time disclosure.
 * Shown when the project contains >= 1 TTS clip on export.
 *
 * Title: "This export contains AI-generated voiceover"
 * Body: EU AI Act Art. 50 reference.
 * Checkbox: "Embed C2PA/XMP AI-generated marker" (default ON).
 * "Learn more" link -> docs/compliance/ai-act.md
 * Buttons: "Export anyway" / "Cancel"
 *
 * TODO: Integration with the export flow via event bus when shipped.
 */

import { useState, useCallback } from "react";
import { Dialog } from "@base-ui-components/react/dialog";
import { Button } from "@/components/ui/button";
import { ExternalLink } from "lucide-react";
import {
  dialogBackdropMotionClassName,
  dialogCenteredPopupMotionClassName,
  dialogViewportClassName,
} from "@/components/ui/dialog-motion";

export interface AiDisclosureResult {
  proceed: boolean;
  embedC2pa: boolean;
}

export interface AiDisclosureModalProps {
  open: boolean;
  ttsClipCount: number;
  onResult: (result: AiDisclosureResult) => void;
}

export function AiDisclosureModal({
  open,
  ttsClipCount,
  onResult,
}: AiDisclosureModalProps) {
  // C2PA checkbox default ON per G8
  const [embedC2pa, setEmbedC2pa] = useState(true);

  const handleExport = useCallback(() => {
    onResult({ proceed: true, embedC2pa });
  }, [onResult, embedC2pa]);

  const handleCancel = useCallback(() => {
    onResult({ proceed: false, embedC2pa: false });
  }, [onResult]);

  return (
    <Dialog.Root
      open={open && ttsClipCount >= 1}
      onOpenChange={(nextOpen) => {
        if (!nextOpen) handleCancel();
      }}
    >
      <Dialog.Portal>
        <Dialog.Backdrop
          className={`fixed inset-0 z-50 bg-[var(--color-fg-primary)/50] ${dialogBackdropMotionClassName}`}
        />
        <Dialog.Viewport className={dialogViewportClassName}>
          <Dialog.Popup
            className={`w-full max-w-md rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] p-6 shadow-lg ${dialogCenteredPopupMotionClassName}`}
          >
            <Dialog.Title className="mb-2 text-lg font-semibold">
              This export contains AI-generated voiceover
            </Dialog.Title>
            <Dialog.Description className="mb-3 text-sm text-[var(--color-fg-muted)]">
              {`This project includes ${ttsClipCount} AI-generated TTS clip${ttsClipCount > 1 ? "s" : ""}. `}
              Under the <strong>EU AI Act</strong> Article 50, content
              generated by AI systems may require disclosure to viewers.
            </Dialog.Description>

            <label className="mb-3 flex cursor-pointer items-center gap-2 text-sm">
              <input
                type="checkbox"
                role="checkbox"
                checked={embedC2pa}
                onChange={(e) => setEmbedC2pa(e.target.checked)}
                className="rounded border-[var(--color-border)]"
                aria-label="Embed C2PA/XMP AI-generated marker"
              />
              <span>Embed C2PA/XMP AI-generated marker</span>
            </label>

            <a
              href="docs/compliance/ai-act.md"
              target="_blank"
              rel="noopener noreferrer"
              className="mb-4 inline-flex items-center gap-1 text-xs text-[var(--color-accent)] hover:underline"
            >
              Learn more
              <ExternalLink className="h-3 w-3" />
            </a>

            <div className="mt-4 flex justify-end gap-2">
              <Button variant="ghost" onClick={handleCancel}>
                Cancel
              </Button>
              <Button onClick={handleExport}>Export anyway</Button>
            </div>
          </Dialog.Popup>
        </Dialog.Viewport>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
