/**
 * AI Disclosure Modal — EU AI Act Article 50 export-time disclosure.
 * Shown when the project contains >= 1 TTS clip on export.
 *
 * Title: "This export contains AI-generated voiceover"
 * Body: EU AI Act Art. 50 reference.
 * Checkbox: "Embed AI-generated voice metadata (XMP)" (default ON).
 * "Learn more" link -> docs/compliance/ai-act.md
 * Buttons: "Export anyway" / "Cancel"
 *
 */

import { Button as AstryxButton } from "@astryxdesign/core/Button";
import { Dialog } from "@astryxdesign/core/Dialog";
import { Switch } from "@astryxdesign/core/Switch";
import { ExternalLink } from "lucide-react";
import { useCallback, useState } from "react";

export interface AiDisclosureResult {
  proceed: boolean;
  embedXmp: boolean;
}

export interface AiDisclosureModalProps {
  open: boolean;
  ttsClipCount: number;
  onResult: (result: AiDisclosureResult) => void;
}

export function AiDisclosureModal({ open, ttsClipCount, onResult }: AiDisclosureModalProps) {
  const [embedXmp, setEmbedXmp] = useState(true);

  const handleExport = useCallback(() => {
    onResult({ proceed: true, embedXmp });
  }, [onResult, embedXmp]);

  const handleCancel = useCallback(() => {
    onResult({ proceed: false, embedXmp: false });
  }, [onResult]);

  return (
    <Dialog
      isOpen={open && ttsClipCount >= 1}
      onOpenChange={(nextOpen) => {
        if (!nextOpen) handleCancel();
      }}
      purpose="form"
      width={448}
      padding={6}
      aria-labelledby="ai-disclosure-title"
      aria-describedby="ai-disclosure-description"
    >
      <div>
        <h2 id="ai-disclosure-title" className="mb-2 text-lg font-semibold">
          This export contains AI-generated voiceover
        </h2>
        <p
          id="ai-disclosure-description"
          className="mb-3 text-sm text-[var(--color-text-secondary)]"
        >
          {`This project includes ${ttsClipCount} AI-generated TTS clip${ttsClipCount > 1 ? "s" : ""}. `}
          Under the <strong>EU AI Act</strong> Article 50, content generated by AI systems may
          require disclosure to viewers.
        </p>

        <div className="mb-3">
          <Switch
            label="Embed AI-generated voice metadata (XMP)"
            value={embedXmp}
            onChange={setEmbedXmp}
          />
        </div>

        <a
          href="docs/compliance/ai-act.md"
          target="_blank"
          rel="noopener noreferrer"
          className="mb-4 inline-flex items-center gap-1 text-xs text-[var(--color-accent)] hover:underline"
        >
          Learn more
          <ExternalLink className="h-3 w-3" />
        </a>

        <div className="mt-4 flex justify-end gap-2">
          <AstryxButton variant="ghost" onClick={handleCancel} label="Cancel">
            Cancel
          </AstryxButton>
          <AstryxButton variant="primary" onClick={handleExport} label="Export anyway">
            Export anyway
          </AstryxButton>
        </div>
      </div>
    </Dialog>
  );
}
