import type { RecordingCertificationSignerKeyMapV3 } from "./recording-v3-certification-manifest";

/** Generated by protected release automation; source checkouts remain fail-closed. */
export const GENERATED_RECORDING_CERTIFICATION_SIGNER_KEYS_V3: RecordingCertificationSignerKeyMapV3 =
  Object.freeze({});
